name: Ddeploy the backend
on:
  push:
    branches: [ main ]
  jobs:
    build:
      runs-pn: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/Checkout@v2
        
        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME  }}
            password: ${{ secrets.DOCKERHUB_TOKEN  }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./docker/Dockerfile.frontend
            build-args:
              - DATABASE_URL=${{ secrets.DATABASE_URL }}
            push: true
            tags: sarwar/user-app-websocket:${{  github.sha  }}